version: '3.8'
services:
  http:
    build: ./http
    container_name: http_c
    ports:
      - '5000:5000'
    volumes:
      - ./http:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true 

